### PR TITLE
Fix bug: HBox of tasklist does not grow at some length

### LINKED ISSUE #70: Bug: HBox of tasklist does not grow after some length

### PR DESCRIPTION
**Pull request by LimJunxue**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/HelpCommand.java [hunk 1]
```diff
@@ -32,7 +34,8 @@
             + HELP_MESSAGE_ADD_DEADLINE + "\n"
             + HELP_MESSAGE_EDIT + "\n"
             + HELP_MESSAGE_FIND + "\n"
-            + HELP_MESSAGE_DELETE + "\n"
+            + HELP_MESSAGE_DELETE_TASK + "\n"
+            + HELP_MESSAGE_DELETE_FIELD + "\n"
```
Comment (maxxng) [inline src/main/java/seedu/address/logic/commands/HelpCommand.java:38]: I have edited the help command already in the new PR.

**Review by maxxng — APPROVED** [review]
